username = input('Имя пользователя:')
print(username)
title  = input('Заголовок заметки:')
print(title)
title  = input('Заголовок заметки:')
print(title)
title  = input('Заголовок заметки:')
print(title)
content = input('Описание заметки:')
print(content)
status = input('Статус заметки:')
print(status)
created_date = input('Дата создания заметки в формате "день-месяц-год":')
print(created_date)
issue_date = input('Дата истечения заметки (дедлайн) в формате "день-месяц-год":')
print(issue_date)