username = ("Имя пользователя:")
title = ("Заголовок заметки:")
content = ("Описание заметки:")
status = ("Статус заметки:")
created_date = ("Дата создания заметки (в формате дд.мм.гг.):")
issue_date = ("Дата истечения заметки (в формате дд.мм.гг.):")

print(username)
print(title)
print(content)
print(status)
print(created_date)
print(issue_date)
