username = input("Имя пользователя:")
title = input("Заголовок заметки:")
content = input("Описание заметки:")
status = input("Статус заметки:")
created_date = input("Дата создания заметки (в формате дд.мм.гг.):")
issue_date = input("Дата истечения заметки (в формате дд.мм.гг.):")

print(username)
print(title)
print(content)
print(status)
print(created_date[0:10])
print(issue_date[0:10])